# Generated by Django 4.1.1 on 2022-09-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='branch',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
