# Generated by Django 4.1.1 on 2022-11-19 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PATIENT', '0004_remove_multipleuploadimages_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipleuploadimages',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='multipleuploadimages',
            name='images',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
