# Generated by Django 4.1.1 on 2022-09-25 12:42

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PATIENT', '0002_patient_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=40)),
                ('date', models.CharField(default='', max_length=40)),
                ('status', models.BooleanField(default=0, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Hedoc', 'Hedoc'), ('Stomach', 'Stomach'), ('Brain', 'Brain'), ('Heart', 'Heart'), ('Liver', 'Liver'), ('Kideney', 'Kideney'), ('Oncho', 'Oncho'), ('Yash', 'Yash')], max_length=255)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_upload', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(default='', max_length=12, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=200)),
                ('potency', models.CharField(choices=[('Q', 'Q'), ('3X', '3X'), ('6X', '6X'), ('6', '6'), ('30', '30'), ('200', '200'), ('1M', '1M'), ('10M', '10M'), ('0/1', '0/1'), ('0/2', '0/2'), ('0/3', '0/3'), ('0/4', '0/4'), ('0/5', '0/5'), ('0/6', '0/6'), ('0/7', '0/7'), ('0/8', '0/8'), ('0/9', '0/9'), ('0/10', '0/10'), ('0/11', '0/11'), ('0/12', '0/12'), ('0/13', '0/13'), ('0/14', '0/14'), ('0/15', '0/15')], max_length=50)),
                ('date', models.DateField()),
                ('durations', models.CharField(choices=[('7 days', '7 days'), ('15 days', '15 days'), ('1 month', '1 month'), ('2 month', '2 month'), ('3 month', '3 month'), ('4 month', '4 month'), ('6month', '6 month')], max_length=50)),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient')),
            ],
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(default='', max_length=12, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
