# Generated by Django 4.1.1 on 2022-09-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('COMMON_APP', '0001_initial'),
        ('PATIENT', '0002_patient_branch'),
        ('DOCTER', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='docterid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DOCTER.docter'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient'),
        ),
    ]
