# Generated by Django 4.1.1 on 2022-09-25 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0001_initial'),
        ('PATIENT', '0002_patient_branch'),
        ('COMMON_APP', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=40)),
                ('date', models.CharField(default='', max_length=40)),
                ('cunsulting', models.BooleanField(default=False)),
                ('extraMedicine', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('docterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DOCTER.docter')),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='MultipleImage',
        ),
    ]
